andrew-saydjari/ApogeeReduction.jl

.gitignore
Project.toml
pipeline.jl
src/ap3D.jl
test/ap3D.jl

use less memory

---

src/cal_build/make_traces_domeflats.jl
src/cal_build/traceExtract.jl
submit_loc_ex.sh

Sped up the trace extraction code by a factor of ~4 using the newer, more stable fitting code. Also added some new diagnostic output plots.

Trace speedup

---

dags/main.py

Automated updates

---

pipeline.jl
pipeline_2d_1d.jl
src/cal_build/make_runlist_quartz_flats.jl
src/cal_build/make_traces_quartzflats.jl
src/cal_build/run_trace_cal.sh
src/run_scripts/run_all.sh

Added in trace extraction of QUARTZFLAT images for both APO and LCO. 
Changed the extraction parameters from DOMEFLAT to QUARTZFLAT results.

Added trace extraction for QUARTZFLATS

---

README.md

Update README.md for new flags

---

src/utils.jl

Update utils.jl to correct slack channel

---

src/run_scripts/make_runlist_all.jl
src/run_scripts/plot_all.jl
src/run_scripts/run_all.sh

Had to re-remind myself how this works so I added a couple comments to make it faster next time.

Add a few comments.

---

pipeline.jl
src/ar3D.jl
src/cal_build/traceExtract.jl

Added `sec_since_mjd` to the ar2D and ar2Dcal files, where mjd_zero=1858-11-17T00:00:00.000

added obs time to ar2D and ar2Dcal files

---

src/ar3D.jl

Edit this so there's less to get out of sync in future

make docstring more accurate

---

pipeline_2d_1d.jl
src/ar1D.jl
src/cal_build/make_traces_domeflats.jl
src/cal_build/make_traces_quartzflats.jl
src/cal_build/traceExtract_GH.jl

Use the newly-defined Gaussian-Hermite trace profiles (measured using sparsePak observations) in both the trace fitting and 1D trace extraction

Gh trace extract

---

src/cal_build/traceExtract_GH.jl

Delete some unused variables (and a couple other very small tweaks).  @KevinMcK95, do you mind glancing at this and making sure none of these are supposed to be used?

delete some unused vars and unecessary copies

---

dags/main.py
src/monitor_scripts/fiber_thrpt.jl

adding in fiber throughput summary in monitor_scripts for future ease (and telescope stability monitoring)

2025 03 26

---

pipeline.jl
pipeline_2d_1d.jl
src/cal_build/make_runlist_darks.jl
src/cal_build/make_runlist_dome_flats.jl
src/cal_build/make_runlist_internal_flats.jl
src/cal_build/make_runlist_quartz_flats.jl
src/run_scripts/make_runlist_all.jl
src/skyline_peaks.jl
src/wavecal.jl

roll back safe_jldsave in 3 places, fix some errant list typing and missing HDF5 imports?

2025 04 09

---

.gitignore
src/cal_build/make_traces_domeflats.jl
src/cal_build/make_traces_quartzflats.jl
src/utils.jl

Fix some bugs from the hot merge.

2025 04 21

---

dags/production.py

airflow-prod <- main

---

README.md

Just documenting things that I found confusing.  Someone should give this a once over before merging.

describe file species

---

metadata/observing_log_viewer/index.html

closes #209 
The link in that thread won't always work as it depends on what I have checked out. We should point to a stable copy that sits on main for using this thing.

little obslog viewer

---

.github/workflows/CI.yml

Does make sense for this project, for the same reasons as #188

don't run on julia nightly

---

src/run_scripts/generate_dashboard.jl
src/run_scripts/plot_all.jl
src/run_scripts/run_all.sh

- Folder the plots in plot_all by mjd
- Generate a basic webpage for viewing the plots.  
- I would like to iterate on this, but it does work. 
- The main thing TODO is getting the calibration plots in there as well.
- Example: https://data.sdss5.org/sas/sdsswork/users/u6035527/outdir/plots/60835/dashboard.html

folder plots by MJD; webpage for viewing

---

metadata/observing_log_viewer/index.html

make it easier to update the SJD

---

metadata/observing_log_viewer/index.html
src/run_scripts/generate_dashboard.jl

Adds a link to each to the other (in the airflow daily).

link back and forth between the observing log viewer the the plotting dashboards

---

README.md
src/cal_build/make_relFlux.jl
src/run_scripts/plot_all.jl

relFlux fix fail if no exposures, add SJD definition to readme

2025 06 20

---

src/skyline_peaks.jl
src/wavecal.jl

Caught a few bugs in the skyline fitting (incorrect parameter centers) and FPI cavity size definitions

Wavelength solution tweaks

---

src/ar1D.jl

still need to add in explicit check that the meta data is equal for the different chips

add metadata to ar1Duni files

---

src/run_scripts/generate_dashboard.jl
src/run_scripts/plot_all.jl

example: https://data.sdss5.org/sas/sdsswork/users/u6035527/outdir/plots/60855/dashboard.html#ar1dunical

sort plots by object type

---

scripts/run/generate_dashboard.jl

This should not change behavior at all; just remove warnings

remove duplicated lines

---

Manifest.toml

This is purely removing packages from the environment that aren't required in `Project.toml`.  A complete run works with these changes.

Remove a bunch of no-longer-required packages from the Manifest.

---

scripts/cal/make_runlist_dome_flats.jl
scripts/cal/make_runlist_quartz_flats.jl
scripts/cal/make_traces_domeflats.jl
scripts/cal/make_traces_quartzflats.jl
scripts/cal/run_trace_cal.sh

This is a basic cleanup of run_trace_cal.sh and adding kwargs to elliminate a few safe_jldsave warnings.  Tested.

Trace script cleanup

---

dags/ar_main.py
scripts/cal/make_traces_from_flats.jl
scripts/daily/generate_dashboard.jl

fixing trace param bug from temp try catch

daily run refines

---

scripts/bulk/make_runlist_all.jl
scripts/cal/make_runlist_darks.jl
scripts/cal/make_runlist_fiber_flats.jl
scripts/cal/make_runlist_internal_flats.jl
scripts/daily/generate_dashboard.jl
src/ar3D.jl

fix domeflat extractions at apo to be dcs like before

Bulk traces

---

scripts/bulk/run_bulk.sh
scripts/daily/run_all.sh
src/ar1D.jl

clean up the sky boss edge and fibertypes

2025 09 18
